version: "3.8"
services:
  voyages-bdd:
    build: ./mysql-bdd
    image: v-bdd
    container_name: mysql-bdd
    networks:
    - v-network
    volumes:
    - v-bdd-data:/var/lib/mysql
  voyages-app:
    build: ./projet-java-web-sql
    image: v-app
    container_name: voyages-app
    depends_on:
    - voyages-bdd
    ports:
    - "9000:8080"
    networks:
    - v-network
networks:
  v-network:
volumes:
  v-bdd-data:
