version: "3.8"
services:
  articles-bdd:
    build: ./articles-bd
    image: articles-b
    container_name: articles-bdd
    networks:
    - v-network
    volumes:
    - v-bdd-data:/var/lib/mysql
    ports:
    - "9020:3306"
 
  # articles-back:
  #   build: ./articles-back
  #   image: v-app
  #   container_name: articles-back
  #   depends_on:
  #   - articles-app
  #   ports:
  #   - "9030:8080"
  #   networks:
  #   - v-network
networks:
  v-network:
volumes:
  v-bdd-data:
